### ISSUE TITLE
mob. v. empty space on the right

### ISSUE THREAD

**Issue by ValeriiKupyna** [OlejnikKristina/Template-MoGo#11]

**Comment by ValeriiKupyna** [comment]
You should delete padding for col in first section

**Comment by OlejnikKristina** [comment]
Thanks ! This remark really was helpful. You even find where exactly problem is =D
It was all because of bootstrap.
How i fixed it
Before:
.row {
    margin-right: -15px;
    margin-left: -15px;
}
After:
.row {
    margin-right: 0;
    margin-left: 0;
}
